#application: directed-cove-374
#version: 1
runtime: python27
threadsafe: true
api_version: 1
instance_class: F4

handlers:
- url: /static
  static_dir: static

- url: /bower_components
  static_dir: bower_components

- url: /admin/.*
  script: admin.application
  login: admin
  secure: always

- url: /app/.*
  script: admin.application
#  login: required
  secure: always

- url: /_ah/login.*
  script: admin.application

#- url: /_ah/login_required
#  script: login_required.py

- url: /sys/.*
  script: admin.application
  login: admin

- url: /signup
  script: main.application
  secure: always

- url: /login
  script: main.application
  secure: always

- url: /forgot
  script: main.application
  secure: always

- url: .*
  script: main.application
  secure: always

builtins:
- deferred: on
- appstats: off

libraries:
- name: jinja2
  version: "latest"

- name: MySQLdb
  version: "latest"

- name: webapp2
  version: "latest"

- name: webob
  version: "1.2.3"

inbound_services:
- warmup

